/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as adminDashboardImport } from './routes/(admin)/dashboard'
import { Route as adminLayoutImport } from './routes/(admin)/_layout'

// Create Virtual Routes

const adminImport = createFileRoute('/(admin)')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const adminRoute = adminImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const authLoginRoute = authLoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const adminDashboardRoute = adminDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => adminRoute,
} as any)

const adminLayoutRoute = adminLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => adminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/(admin)': {
      preLoaderRoute: typeof adminImport
      parentRoute: typeof rootRoute
    }
    '/(admin)/_layout': {
      preLoaderRoute: typeof adminLayoutImport
      parentRoute: typeof adminRoute
    }
    '/(admin)/dashboard': {
      preLoaderRoute: typeof adminDashboardImport
      parentRoute: typeof adminImport
    }
    '/(auth)/login': {
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  adminRoute.addChildren([adminDashboardRoute]),
  authLoginRoute,
])

/* prettier-ignore-end */
