/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StoreImport } from './routes/_store'
import { Route as IndexImport } from './routes/_index'
import { Route as AuthImport } from './routes/_auth'
import { Route as AdminImport } from './routes/_admin'
import { Route as IndexIndexImport } from './routes/_index/index'
import { Route as AuthRegisterImport } from './routes/_auth/register'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AdminDashboardImport } from './routes/_admin.dashboard'
import { Route as IndexProductsIndexImport } from './routes/_index/products/index'
import { Route as IndexCollectionsIndexImport } from './routes/_index/collections/index'
import { Route as IndexProductsIdImport } from './routes/_index/products/$id'
import { Route as IndexCollectionsIdImport } from './routes/_index/collections/$id'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const StoreRoute = StoreImport.update({
  id: '/_store',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/_index',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/_admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexIndexRoute = IndexIndexImport.update({
  path: '/',
  getParentRoute: () => IndexRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AdminDashboardRoute = AdminDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

const IndexProductsIndexRoute = IndexProductsIndexImport.update({
  path: '/products/',
  getParentRoute: () => IndexRoute,
} as any)

const IndexCollectionsIndexRoute = IndexCollectionsIndexImport.update({
  path: '/collections/',
  getParentRoute: () => IndexRoute,
} as any)

const IndexProductsIdRoute = IndexProductsIdImport.update({
  path: '/products/$id',
  getParentRoute: () => IndexRoute,
} as any)

const IndexCollectionsIdRoute = IndexCollectionsIdImport.update({
  path: '/collections/$id',
  getParentRoute: () => IndexRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_index': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_store': {
      preLoaderRoute: typeof StoreImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_admin/dashboard': {
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof AdminImport
    }
    '/_auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/register': {
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthImport
    }
    '/_index/': {
      preLoaderRoute: typeof IndexIndexImport
      parentRoute: typeof IndexImport
    }
    '/_index/collections/$id': {
      preLoaderRoute: typeof IndexCollectionsIdImport
      parentRoute: typeof IndexImport
    }
    '/_index/products/$id': {
      preLoaderRoute: typeof IndexProductsIdImport
      parentRoute: typeof IndexImport
    }
    '/_index/collections/': {
      preLoaderRoute: typeof IndexCollectionsIndexImport
      parentRoute: typeof IndexImport
    }
    '/_index/products/': {
      preLoaderRoute: typeof IndexProductsIndexImport
      parentRoute: typeof IndexImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AdminRoute.addChildren([AdminDashboardRoute]),
  AuthRoute.addChildren([AuthLoginRoute, AuthRegisterRoute]),
  IndexRoute.addChildren([
    IndexIndexRoute,
    IndexCollectionsIdRoute,
    IndexProductsIdRoute,
    IndexCollectionsIndexRoute,
    IndexProductsIndexRoute,
  ]),
  AboutLazyRoute,
])

/* prettier-ignore-end */
